[package]
name = "index"
version = "0.1.0"
edition = "2021"

[dependencies]
core = {path = "../core"}
intelligence = { path = "../intelligence"}
petgraph = {version = "0.6.4", default-features = false}
tokenizers = "0.21"
ahash = "0.8"

[dev-dependencies]
expect-test = "1.4"